### ISSUE TITLE
How do I read cookies on server?

### ISSUE THREAD

**Issue by developer239** [thereactivestack/react-cookie#39]
How do I read cookies on server?

I save cookie in action creator:

`cookie.save('userId', userId);`

How do I load it on server? I know that I can access cookies in `req.cookies` but I want to keep the logic in the right place. I do not want to edit server.js file.
When I do `console.log(cookie.load('userId')` I get undefined in server console.

**Comment by michaljarnot** [comment]
I decided to create custom middleware because of this stackoverflow answer: `http://stackoverflow.com/questions/34038726/redux-router-how-to-replay-state-after-refresh`

**Comment by eXon** [comment]
Are you using `plugToRequest`? (look at the readme)

**Comment by michaljarnot** [comment]
I am but when I do `const userId = cookie.load('userId')` I get undefined.

**Comment by jonathan-stone** [comment]
Thanks for writing react-cookie! It's been very helpful on the client side.

I'm trying to figure out how to use it on the server side. What does `plugToRequest()` do? The readme doesn't say. "You can also plug it directly" - I don't understand what that means. Plug what into what?

Also, does "(require the cookieParser middleware)" mean that we need to use cookieParser in order for plugToRequst() to do whatever it does? What's the point of plugToRequest if we can just read the cookie from the request on the server side thanks to cookieParser?

I guess a more complete example that showed what you do with plugToRequest, or what it enables you do do, would be helpful.

**Comment by outlawshade** [comment]
Try ```
reactCookie.setRawCookie(req.headers.cookie);
            let user = reactCookie.load('username-session');
```

**Comment by developer239** [comment]
I resolved this problem like this:

https://github.com/mz026/universal-redux-template/issues/35

**Comment by jonathan-stone** [comment]
Hi @eXon, to clarify, this issue is a request for improved documentation. I'm curious, why it has been closed with no change to the docs? I guess I'm being lazy in that I could read the source and file a PR with a little more info in the documentation source.

@developer239, I did something similar, but I wonder if react-cookie would have made adding that code unnecessary.

**Comment by eXon** [comment]
@jonathan-stone are you saying the `plugToRequest` is broken? Because how to use it is kinda the first thing explained in the readme.

**Comment by jonathan-stone** [comment]
@eXon  No, I'm not saying anything like that. My question is just:

**What does `plugToRequest` do?** 

Pourquoi est-ce que je voudrais appeler ce function? Qu'est-ce que ca fait? Le documentation dit seulement qu'on peut l'appeler, main ne dit rien de ce que fait le function, ou ce que je pourrais faire apres l'avoir appele.

**Comment by eXon** [comment]
@jonathan-stone just took the time to improve the readme

plugToRequest is loading your user cookies so you can do server-rendering and have the same result. Everytime you load a cookie, it will simulate the same result on Node.js.

**Comment by jonathan-stone** [comment]
Thanks @eXon !
