### ISSUE TITLE
Use with Hapi

### ISSUE THREAD

**Issue by mjw56** [thereactivestack/react-cookie#41]
Hi,

Thanks for making this library, it is super helpful.

Right now when I try to use this with Hapi, it looks like the cookies are not stored when using `plugToRequest`.

I think this is because hapi stores the cookies on `request.state` and the function is not looking there. 

Any thoughts on this?

Cheers

**Comment by eXon** [comment]
You can use `reactCookie.setRawCookie` with the raw cookie header you receive.

If you would like to make a pull request to support Hapi I would be happy to merge it :)
