### ISSUE TITLE
Long numeric strings converted to integer

### ISSUE THREAD

**Issue by Elijen** [thereactivestack/react-cookie#44]
It seems that long numeric strings are converted to integers which can cause overflow. For example: `4823425323423554889` becomes `4823425323423554000`.

If the implicit string -> integer conversion is by design, the library should check `Number.MAX_VALUE` to make sure there is no information lost in the conversion.

**Comment by Elijen** [comment]
I see this is a duplicate of #33 and #35. Didn't know the cookie values are treated as JSON by default.

**Comment by eXon** [comment]
I'll add a notice on the readme because the fix is not obvious

**Comment by eXon** [comment]
Plain numbers are no more parsed when loaded so this problem should disappear
