### ISSUE TITLE
Use ES2015 export

### ISSUE THREAD

**Issue by BrandonBoone** [thereactivestack/react-cookie#45]
I'd like to be able to [import specific members from the library](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import).

`import { select } from 'react-cookie';`

This would enable tree shaking to work in bundlers like [Webpack 2.0](https://webpack.js.org), [Rollup](https://github.com/rollup/rollup), ect.

See [export](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/export)

**Comment by eXon** [comment]
I'm also heavily using import and ES2015+ but this library is so small and simple I don't see the benefit of doing it. There is not much thing to shake off the tree here.

It shouldn't prevent you from importing a specific function though. Is it?

**Comment by eXon** [comment]
I already had a nice setup to migrate with so I ran with it. Enjoy :)
