### ISSUE TITLE
Logical error

### ISSUE THREAD

**Issue by DulebovArtem** [thereactivestack/react-cookie#50]
src=>cookie.js
const IS_NODE = typeof document === 'undefined' || (typeof module !== 'undefined' && module.exports);

When you are defining IS_NODE constant you have module and module.exports available, so the code sets wrong value to IS_NODE (it is always not 'false')
Also please check how logical operators work

typeof document === 'undefined' --> false
typeof module !== 'undefined' --> true
module.exports --> object

(false || (true && object)) === object

So as a result IS_NODE is always a reference to module.exports
And cookie would never be saved to document because of this code

 if (!IS_NODE) {
    document.cookie = cookie.serialize(name, _rawCookie[name], opt);
  }

Please Make Is_Node checking as a function, something like that

function IS_NODE(){
  return typeof document === 'undefined' || (typeof module !== 'undefined' && !!module.exports);
}

**Comment by rosskevin** [comment]
Confirmed, we can no longer read signed cookies in the browser due to this latest change.

**Comment by eXon** [comment]
I though I fixed this. Sorry about that, 1.0.3 should be fine.

**Comment by eXon** [comment]
@DulebovArtem JavaScript is a different beast than most language. `if (module.exports)` and `if (!!module.exports)` are exactly the same. The boolean result will not change.
