### ISSUE TITLE
MaxAge differs between client and server

### ISSUE THREAD

**Issue by ctirs** [thereactivestack/react-cookie#53]
Hi,

i had the following issue that when i write cookies at the Servers they vanished nearly immediately.
It turned out that when i multiplied maxAge with 1000 it was correct (but still very ugly).
So at the client maxAge is in seconds and at the server in ms.

**Comment by eXon** [comment]
You are probably using express.js and unlike the Web standard, it sets the cookie max-age in ms instead of secs. Maybe we could patch it for that specific use case because so many people are using it with express.js.

**Comment by ctirs** [comment]
yes indeed we are using express.

Maybe the a good solution could be to internally only use the expires field. Which works correctly at client and at the server.

**Comment by eXon** [comment]
It should adjust the value it sends to express now to be in milliseconds
