### ISSUE TITLE
Unable to grab data from parsed JSON

### ISSUE THREAD

**Issue by carterwarrengravitas** [thereactivestack/react-cookie#57]
So far this plugin is awesome. But I ran into a snag. 

This alert gives me back an object no problem: 
`const obj = cookie.load("person", {});
    alert( obj );`
Parsed data in the alert box:
`{"primary_name":{"full":"Ryan Mitch Smith","prefix":"Mr","first":"Ryan","middle":"Mitch","last":"Smith"}`

However, when I do `alert ( obj.primary_name );` it returns as undefined.

I feel like I'm missing something simple.

**Comment by eXon** [comment]
The second parameter of load is a boolean for the `shouldBeParsed` option. Remove it because you're probably getting the string instead of the object.

**Comment by carterwarrengravitas** [comment]
Thanks. Cleared it up.
