### ISSUE TITLE
cookie.load() not working between pages

### ISSUE THREAD

**Issue by tomellwood** [thereactivestack/react-cookie#60]
In my react app I'm setting cookies based on the url, for example '../page-one'.

If I enter the app on page '../page-one', cookie.load('cookieName') works fine and I can check if the cookie exists; but I then need to check for another cookie when I navigate to another page (using react-router).

I've tried running cookie.load('cookieName') in componentDidUpdate() to make sure I'm on the new page with new params, i.e. '../page-two', but it still returns the cookie value from the previous check.

The only way I can get it to work is by refreshing the page and it checks for the cookie against the '../page-two' path.

Are there any solutions to get the expected results from cookie.load('cookieName') when the component receives new props?

Thanks.

**Comment by eXon** [comment]
You have to use the `path` option to `/` when saving if you want your cookie accessible everywhere:

```js
cookie.save('cookieName', 'test', { path: '/' });
```

**Comment by tomellwood** [comment]
What if I don't want the cookie to be accessible everywhere? I set the path to the relevant page with

`cookie.save('cookieName', 'test', { path: '/page-one' });`

Then I'll check to see if the cookie exists in componentDidMount when on the correct path '/page-one'

`cookie.load('cookieName')`

Then when using react-router and navigating to another page, cookie.load('cookieName') will still return the value of the cookie saved with the path of '/page-one', no matter what method I use, render(), componentDidUpdate(), etc. The only time I could get it to return 'undefined' is if I refresh the page.

**Comment by eXon** [comment]
@tomellwood The browser is responsible for giving or not giving the available cookies. There is no cache within react-cookie on the value. It is asking the browser every single time.

**Comment by tomellwood** [comment]
@eXon It's fine, I resorted to writing my own function to read in cookies, this plugin just doesn't seem to work when saving/loading cookies with a path other than '/'.

I don't think you understood the issue I was having, if you could replicate what I was experiencing above it might be easier for you to troubleshoot.

**Comment by eXon** [comment]
@tomellwood maybe if you give me an example i can take a look

React router is using push/pop state and how the browser react to thoses changes without a page refresh is out of scope of this library. As I said before, the browser is respo sible for enforcing the cookie path.

I hope it helps you
