### ISSUE TITLE
Cookie cookie.load doesn't work after browser is closed and reopened

### ISSUE THREAD

**Issue by jennykortina** [thereactivestack/react-cookie#69]
Hey,

I'm testing in chrome and the cookie comes back as set if once I set it, but if I close the browser and reopen it the cookie comes back as undefined.  Gist [here](https://gist.github.com/jennykortina/2ab49a68e5a39967c7084ac45fa54007)

The cookie is named "dismissed" I followed your example, just not sure to have it persist after browser is closed and reopened.

Thanks!

**Comment by eXon** [comment]
By default, a cookie is a session cookie (they are destroyed once the browser is closed). If you want them to stick, you have to use the `expires` (javascript date) or `maxAge` (seconds from now) option.
