### ISSUE TITLE
Cookies wont get removed if I refresh the browser

### ISSUE THREAD

**Issue by johhansantana** [thereactivestack/react-cookie#70]
Using google chrome

Cookies once set in react and removed successfully if you don't refresh the browser

Once the cookies are set and I refresh the browser, if I try to remove them they don't get removed.

```javascript
import cookie from "react-cookie";
```

```javascript
logout() {
  console.log("loging out");
  cookie.remove("userId");
  cookie.remove("authToken");
  Router.push("/");
}
```

```html
<li className="nav-item">
  <a onClick={this.logout} className="nav-link">Logout</a>
</li>
```

**Comment by johhansantana** [comment]
had to add `path: '/'` to everything to be able to get it working.

**Comment by umair-khanzada** [comment]
@johhansantana I am facing the same issue as you mention above, I also tried your solution add <br />`{path: '/'}` but didn't success, you can check my code as well.

```
login(){
    cookie.save('token', res.data.token);

    //also tried with config object but didn't success
    //cookie.save('token', res.data.token, {path: '/'});
}

logout(){
    cookie.remove('token');

    //also tried with config object but didn't success
    //cookie.remove('token', res.data.token, {path: '/'});
}
```

**Comment by MathiasGilson** [comment]
Hi @umair-khanzada 
According to the doc the prototype of the remove function is 
`remove(name, [options])`
So you should try 
`cookie.remove('token', {path: '/'})`
In short, don't pass the `res.data.token` in your request

**Comment by luispastendev** [comment]
I was having the same problem, I didn't really understand why when deleting the cookies the configuration argument must also be passed, it would be quite good if they specified that in the documentation because when reproducing that error the first thing you think about is that it is a bug !, thanks for everything!
